import type {Metadata} from 'next';
import {Inter, Space_Grotesk} from 'next/font/google';
import './globals.css';

const geistInter = Inter({
    variable: '--font-geist-inter',
    subsets: ['latin'],
});

const geistSpaceGrotesk = Space_Grotesk({
    variable: '--font-geist-space-grotesk',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'CodeLab | Blog',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='pt-br'>
        <body
            className={`${geistInter.variable} ${geistSpaceGrotesk.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
